const map=L.map("map").setView([41.7151,44.8271],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
const groups={mosque:L.layerGroup().addTo(map),food:L.layerGroup().addTo(map),place:L.layerGroup().addTo(map)};let places=[],userLat=null,userLng=null,userAccuracy=null,userMarker=null,userCircle=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const nav=p=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.lat+","+p.lng)}&travelmode=driving`;
function tags(p){let a=[];if(p.verification==="verified_source")a.push("✓ Source found");else if(p.verification==="business_current")a.push("✓ Current listing");else a.push("⚠ Unverified");if(p.type==="mosque"){if(p.sect)a.push("🕌 "+p.sect);if(p.toilet)a.push("🚻 Toilet");if(p.wudu)a.push("💧 Wudu");if(p.wheelchair)a.push("♿ Wheelchair");if(p.women)a.push("👩 Women");if(p.friday)a.push("🕌 Friday")}if(p.type==="food"){if(p.halal)a.push("☪ Halal");if(p.porkFree)a.push("🚫 Pork-free");if(p.vegetarian)a.push("🥗 Vegetarian");if(p.cheap)a.push("💰 Cheap");if(p.atmosphere)a.push("🙂 Nice atmosphere");if(p.delicious)a.push("⭐ Very delicious")}if(p.type==="place"){if(p.entertainment)a.push("🎡 "+p.entertainment);if(p.nature)a.push("🌿 "+p.nature);if(p.religion)a.push("🕊 "+p.religion);if(p.historical)a.push("🏛 Historical");if(p.interesting)a.push("💡 Interesting")}return a.map(x=>`<span>${esc(x)}</span>`).join("")}
function distanceKm(p){if(userLat===null)return null;const R=6371,dLat=(p.lat-userLat)*Math.PI/180,dLon=(p.lng-userLng)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(userLat*Math.PI/180)*Math.cos(p.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function popup(p){let d=distanceKm(p);return `<div class="popup"><h3>${esc(p.name)}</h3><div class="badges">${tags(p)}</div>${d!==null?`<p>📏 <b>${d<10?d.toFixed(1):Math.round(d)} km</b> from you</p>`:""}${p.hours?`<p><b>Hours:</b> ${esc(p.hours)}</p>`:""}${p.address?`<p>📍 ${esc(p.address)}</p>`:""}${p.phone?`<p>☎ ${esc(p.phone)}</p>`:""}${p.website?`<p>🌐 <a href="${esc(p.website)}" target="_blank" rel="noopener">Website</a></p>`:""}<p>${esc(p.notes||"")}</p><a class="nav" href="${nav(p)}" target="_blank" rel="noopener">🧭 Navigate with Google Maps</a><p class="small">Source: ${esc(p.source||"")}</p></div>`}
function filterValues(type){const box=document.getElementById(type+"Filters");return box?[...box.querySelectorAll("[data-filter]:checked")].map(x=>x.dataset.filter):[]}
function match(p){const f=filterValues(p.type);if(!f.length)return true;if(p.type==="mosque"||p.type==="food")return f.every(x=>p[x]===true);return f.every(x=>x==="historical"?p.historical===true:x==="interesting"?p.interesting===true:!!p[x])}
function activeDistance(){return document.querySelector('input[name="distance"]:checked')?.value||"all"}
function inDistance(p){if(activeDistance()==="all"||userLat===null)return true;return distanceKm(p)<=Number(activeDistance())}
function makeMarker(p){let ic=p.type==="mosque"?"🕌":p.type==="food"?"🍴":"⭐",near=userLat!==null&&distanceKm(p)<=50;let c="emoji-marker"+(near?" nearby-blink":"");return L.marker([p.lat,p.lng],{title:p.name,icon:L.divIcon({className:c,html:`<div class="marker-icon">${ic}</div>`,iconSize:[115,115],iconAnchor:[57,105],popupAnchor:[0,-100]})}).bindPopup(popup(p))}
function render(){Object.values(groups).forEach(g=>g.clearLayers());for(const p of places){const layer=document.querySelector(`[data-layer="${p.type}"]`);if(!layer||!layer.checked||!match(p)||!inDistance(p))continue;makeMarker(p).addTo(groups[p.type])}}
function visibility(){for(const t of ["mosque","food","place"]){const layer=document.querySelector(`[data-layer="${t}"]`),box=document.getElementById(t+"Filters");if(box)box.style.display=layer&&layer.checked?"block":"none"}render()}
for(const x of document.querySelectorAll("[data-layer]"))x.addEventListener("change",visibility);for(const x of document.querySelectorAll("[data-filter]"))x.addEventListener("change",render);for(const x of document.querySelectorAll('input[name="distance"]'))x.addEventListener("change",render);
document.getElementById("locateBtn").addEventListener("click",()=>{const s=document.getElementById("locationStatus");if(!navigator.geolocation){s.textContent="GPS is not available in this browser.";return}s.textContent="Requesting your location…";navigator.geolocation.getCurrentPosition(pos=>{userLat=pos.coords.latitude;userLng=pos.coords.longitude;userAccuracy=pos.coords.accuracy;const ll=[userLat,userLng];if(userMarker)map.removeLayer(userMarker);if(userCircle)map.removeLayer(userCircle);userMarker=L.marker(ll,{icon:L.divIcon({className:"emoji-marker",html:'<div class="marker-icon">📍</div>',iconSize:[115,115],iconAnchor:[57,105]})}).addTo(map).bindPopup("📍 You are here").openPopup();userCircle=L.circle(ll,{radius:userAccuracy||30,weight:1}).addTo(map);map.setView(ll,14);s.textContent=`📍 Location found. Nearby places within 50 km are blinking. Accuracy about ${Math.round(userAccuracy)} m.`;render()},()=>s.textContent="Location unavailable. Allow GPS access and try again.",{enableHighAccuracy:true,timeout:15000,maximumAge:30000})});

// Community "Create new place" tool. Static GitHub Pages compatible.
const FORM_ENDPOINT="https://formsubmit.co/ajax/caucasfactory@yahoo.com";
let createMode=false,selectedPoint=null,pendingMarker=null;
const modal=document.getElementById("createModal"),pencilBtn=document.getElementById("pencilBtn"),createStatus=document.getElementById("createStatus"),dynamicFields=document.getElementById("dynamicFields"),newType=document.getElementById("newType"),createForm=document.getElementById("createForm"),saveNew=document.getElementById("saveNew"),createFormArea=document.getElementById("createFormArea"),createHint=document.getElementById("createHint");
const field=(label,name,type="text",extra="")=>`<div class="field"><label>${label}</label><input type="${type}" name="${name}" ${extra}></div>`;
const check=(label,name)=>`<label class="check-field"><input type="checkbox" name="${name}" value="true"> ${label}</label>`;
function buildFields(type){
 if(type==="mosque") dynamicFields.innerHTML=`<div class="field"><label>Name *</label><input name="name" required placeholder="Mosque / prayer room name"></div>${field("Sect (optional)","sect")}
 <div class="check-grid">${check("🚻 Toilet","toilet")}${check("💧 Wudu","wudu")}${check("♿ Wheelchair","wheelchair")}${check("👩 Women's area","women")}${check("🟢 Open","open")}${check("🕌 Friday prayer","friday")}${check("🅿 Parking","parking")}</div>
 ${field("Working / prayer hours","hours","text","placeholder=07:00–22:00")}${field("Address","address")}${field("Telephone","phone","tel")}${field("Website","website","url","placeholder=https://...")}<div class="field"><label>Notes</label><textarea name="notes" placeholder="Anything the visitor should know"></textarea></div>`;
 else if(type==="food") dynamicFields.innerHTML=`<div class="field"><label>Name *</label><input name="name" required placeholder="Restaurant / food place name"></div>${field("Cuisine","cuisine","text","placeholder=Turkish, Azerbaijani, Indian…")}
 <div class="check-grid">${check("☪ Halal","halal")}${check("🚫 Pork-free","porkFree")}${check("🥗 Vegetarian","vegetarian")}${check("💰 Cheap","cheap")}${check("🙂 Nice atmosphere","atmosphere")}${check("⭐ Very delicious","delicious")}</div>
 ${field("Working hours","hours")}${field("Address","address")}${field("Telephone","phone","tel")}${field("Website","website","url","placeholder=https://...")}<div class="field"><label>Notes</label><textarea name="notes" placeholder="Cuisine details, special information, etc."></textarea></div>`;
 else if(type==="place") dynamicFields.innerHTML=`<div class="field"><label>Name *</label><input name="name" required placeholder="Interesting place name"></div>${field("Region","region","text","placeholder=Adjara, Guria, Imereti…")}
 <div class="field"><label>Entertainment</label><select name="entertainment"><option value="">—</option><option>children</option><option>adult</option><option>any age</option></select></div>
 <div class="field"><label>Good nature</label><select name="nature"><option value="">—</option><option>nice</option><option>good</option><option>very good</option></select></div>
 ${field("Religion (if relevant)","religion","text","placeholder=Christian, Islamic, Hindu…")}<div class="check-grid">${check("🏛 Historical","historical")}${check("💡 Interesting","interesting")}</div>
 ${field("Hours / visiting time","hours")}${field("Address","address")}${field("Telephone","phone","tel")}${field("Website","website","url","placeholder=https://...")}<div class="field"><label>Notes</label><textarea name="notes" placeholder="Why this place is useful or interesting"></textarea></div>`;
 else dynamicFields.innerHTML="";
}
function openCreate(){
 createMode=true;selectedPoint=null;newType.value="";buildFields("");createForm.reset();newType.value="";buildFields("");createFormArea.hidden=true;modal.hidden=false;document.body.classList.add("create-active");
 createStatus.textContent="✎ Pencil mode is active. Click the exact point on the map where the new place is located.";createHint.textContent="1. Click a point on the map.  2. Coordinates are captured automatically.  3. The information form will appear.";
 setTimeout(()=>map.invalidateSize(),50)
}
function closeCreate(){createMode=false;selectedPoint=null;modal.hidden=true;document.body.classList.remove("create-active");createFormArea.hidden=true;if(pendingMarker){map.removeLayer(pendingMarker);pendingMarker=null}}
pencilBtn.addEventListener("click",openCreate);document.getElementById("closeCreate").addEventListener("click",closeCreate);document.getElementById("modalBackdrop").addEventListener("click",closeCreate);
newType.addEventListener("change",()=>{buildFields(newType.value);if(selectedPoint)createStatus.textContent=`📍 Coordinates: ${selectedPoint.lat.toFixed(6)}, ${selectedPoint.lng.toFixed(6)}. Complete the information and save.`});
map.on("click",e=>{
 if(!createMode||selectedPoint)return;
 selectedPoint={lat:Number(e.latlng.lat.toFixed(6)),lng:Number(e.latlng.lng.toFixed(6))};
 if(pendingMarker)map.removeLayer(pendingMarker);
 pendingMarker=L.marker([selectedPoint.lat,selectedPoint.lng],{draggable:false}).addTo(map).bindPopup("📍 New place target").openPopup();
 createStatus.textContent=`📍 Coordinates captured: ${selectedPoint.lat.toFixed(6)}, ${selectedPoint.lng.toFixed(6)}. Now choose the layer below.`;
 createHint.textContent="Choose the layer, complete its information, enter your email, then press Save and send.";
 createFormArea.hidden=false;
 setTimeout(()=>newType.focus(),100);
});
function bool(v){return v===true}
function recordFromForm(fd){const type=fd.get("type");const r={id:`community-${Date.now()}`,type,name:fd.get("name")?.trim()||"",lat:selectedPoint.lat,lng:selectedPoint.lng,verification:"candidate",source:"Community submission via Caucasus Traveler",coordinateStatus:"map-click",submittedBy:fd.get("email")?.trim()||"",notes:fd.get("notes")?.trim()||""};
 if(type==="mosque")Object.assign(r,{sect:fd.get("sect")?.trim()||"",toilet:fd.get("toilet")==="true",wudu:fd.get("wudu")==="true",wheelchair:fd.get("wheelchair")==="true",women:fd.get("women")==="true",open:fd.get("open")==="true",friday:fd.get("friday")==="true",parking:fd.get("parking")==="true",hours:fd.get("hours")?.trim()||"",address:fd.get("address")?.trim()||"",phone:fd.get("phone")?.trim()||"",website:fd.get("website")?.trim()||""});
 if(type==="food")Object.assign(r,{cuisine:fd.get("cuisine")?.trim()||"",halal:fd.get("halal")==="true",porkFree:fd.get("porkFree")==="true",vegetarian:fd.get("vegetarian")==="true",cheap:fd.get("cheap")==="true",atmosphere:fd.get("atmosphere")==="true",delicious:fd.get("delicious")==="true",hours:fd.get("hours")?.trim()||"",address:fd.get("address")?.trim()||"",phone:fd.get("phone")?.trim()||"",website:fd.get("website")?.trim()||""});
 if(type==="place")Object.assign(r,{region:fd.get("region")?.trim()||"",interesting:fd.get("interesting")==="true",historical:fd.get("historical")==="true",religion:fd.get("religion")?.trim()||"",nature:fd.get("nature")||"",entertainment:fd.get("entertainment")||"",hours:fd.get("hours")?.trim()||"",address:fd.get("address")?.trim()||"",phone:fd.get("phone")?.trim()||"",website:fd.get("website")?.trim()||""});
 return r}
createForm.addEventListener("submit",async e=>{e.preventDefault();if(!selectedPoint){createStatus.textContent="⚠ Please click a point on the map first.";return}if(!newType.value){createStatus.textContent="⚠ Please choose Prayer, Food, or Interesting place.";return}const email=document.getElementById("submitterEmail").value.trim();if(!email)return;const fd=new FormData(createForm);const record=recordFromForm(fd);const subject=`the new coordinate added by${email}`;const payload={_subject:subject,_replyto:email,email,message:JSON.stringify(record,null,2),database_record:JSON.stringify(record,null,2),submission_type:"Caucasus Traveler community place submission",_captcha:false,_honey:fd.get("_honey")||""};saveNew.disabled=true;saveNew.textContent="⏳ Sending…";createStatus.textContent="Sending your information…";try{const res=await fetch(FORM_ENDPOINT,{method:"POST",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok||data.success===false)throw new Error(data.message||"Submission failed");createStatus.innerHTML="✅ Thank you for your information!<br><br>In a short time we will process your information. If the place is added or updated on the map, you will be informed by email.";saveNew.textContent="✓ Sent";createForm.reset();newType.value="";dynamicFields.innerHTML="";setTimeout(closeCreate,4500)}catch(err){console.error(err);createStatus.textContent="⚠ Could not send. Please check your internet connection and try again.";saveNew.disabled=false;saveNew.textContent="💾 Save and send"}});

// Filters start open. The user can collapse/expand them with the arrow.
const filterCollapseBtn=document.getElementById("filterCollapseBtn"),filterContent=document.getElementById("filterContent");
filterCollapseBtn.addEventListener("click",()=>{const open=filterCollapseBtn.getAttribute("aria-expanded")==="true";filterCollapseBtn.setAttribute("aria-expanded",String(!open));filterCollapseBtn.textContent=open?"⌄":"⌃";filterCollapseBtn.title=open?"Show filters":"Hide filters";filterContent.style.display=open?"none":"block"});
fetch("data/places.json").then(r=>r.json()).then(d=>{places=d;visibility()}).catch(()=>document.getElementById("locationStatus").textContent="Could not load data/places.json.");
