const map=L.map("map").setView([41.7151,44.8271],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
const groups={mosque:L.layerGroup().addTo(map),food:L.layerGroup().addTo(map),place:L.layerGroup().addTo(map)};let places=[];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const nav=p=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.lat+","+p.lng)}&travelmode=driving`;
function tags(p){let a=[];if(p.verification==="verified_source")a.push("✓ Source found");else if(p.verification==="business_current")a.push("✓ Current listing");else a.push("⚠ Unverified");
if(p.type==="mosque"){if(p.sect)a.push("🕌 "+p.sect);if(p.toilet)a.push("🚻 Toilet");if(p.wudu)a.push("💧 Wudu");if(p.wheelchair)a.push("♿ Wheelchair");if(p.women)a.push("👩 Women");if(p.friday)a.push("🕌 Friday")}
if(p.type==="food"){if(p.halal)a.push("☪ Halal");if(p.porkFree)a.push("🚫 Pork-free");if(p.vegetarian)a.push("🥗 Vegetarian");if(p.cheap)a.push("💰 Cheap");if(p.atmosphere)a.push("🙂 Nice atmosphere");if(p.delicious)a.push("⭐ Very delicious")}
if(p.type==="place"){if(p.entertainment)a.push("🎡 "+p.entertainment);if(p.nature)a.push("🌿 "+p.nature);if(p.religion)a.push("🕊 "+p.religion);if(p.historical)a.push("🏛 Historical");if(p.interesting)a.push("💡 Interesting")}return a.map(x=>`<span>${esc(x)}</span>`).join("")}
function popup(p){return `<div class="popup"><h3>${esc(p.name)}</h3><div class="badges">${tags(p)}</div>${p.hours?`<p><b>Hours:</b> ${esc(p.hours)}</p>`:""}${p.address?`<p>📍 ${esc(p.address)}</p>`:""}${p.phone?`<p>☎ ${esc(p.phone)}</p>`:""}${p.website?`<p>🌐 <a href="${esc(p.website)}" target="_blank">Website</a></p>`:""}<p>${esc(p.notes||"")}</p><a class="nav" href="${nav(p)}" target="_blank">🧭 Navigate with Google Maps</a><p class="small">Source: ${esc(p.source)}</p></div>`}
function fs(type){return [...document.querySelectorAll(`[data-filter]:checked`)].filter(x=>x.closest(".filter-group")?.id===type+"Filters").map(x=>x.dataset.filter)}
function match(p){let f=fs(p.type);if(!f.length)return true;if(p.type==="mosque"||p.type==="food")return f.every(x=>p[x]===true);return f.every(x=>x==="historical"?p.historical===true:x==="interesting"?p.interesting===true:!!p[x])}
function render(){Object.values(groups).forEach(g=>g.clearLayers());places.forEach(p=>{if(!document.querySelector(`[data-layer="${p.type}"]`).checked||!match(p))return;let ic=p.type==="mosque"?"🕌":p.type==="food"?"🍴":"⭐";L.marker([p.lat,p.lng],{title:p.name,icon:L.divIcon({className:"emoji-marker",html:`<div class="marker-icon">${ic}</div>`,iconSize:[48,48],iconAnchor:[24,44],popupAnchor:[0,-40]})}).bindPopup(popup(p)).addTo(groups[p.type])})}
function visibility(){["mosque","food","place"].forEach(t=>document.getElementById(t+"Filters").style.display=document.querySelector(`[data-layer="${t}"]`).checked?"block":"none");render()}
document.querySelectorAll("[data-layer]").forEach(x=>x.onchange=visibility);document.querySelectorAll("[data-filter]").forEach(x=>x.onchange=render);
document.getElementById("locateBtn").onclick=()=>{let s=document.getElementById("locationStatus");if(!navigator.geolocation){s.textContent="GPS is not available in this browser.";return}s.textContent="Requesting location…";navigator.geolocation.getCurrentPosition(pos=>{let ll=[pos.coords.latitude,pos.coords.longitude];L.marker(ll,{icon:L.divIcon({className:"emoji-marker",html:'<div class="marker-icon">📍</div>',iconSize:[48,48],iconAnchor:[24,44]})}).addTo(map).bindPopup("📍 You are here").openPopup();L.circle(ll,{radius:pos.coords.accuracy||30}).addTo(map);map.setView(ll,15);s.textContent=`📍 Location found (about ${Math.round(pos.coords.accuracy)} m accuracy).`},()=>s.textContent="Location unavailable. Allow GPS access and try again.",{enableHighAccuracy:true,timeout:15000,maximumAge:30000})};
fetch("data/places.json").then(r=>r.json()).then(d=>{places=d;visibility()});
