const map=L.map("map").setView([41.7151,44.8271],11);
L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap contributors"}).addTo(map);
const groups={mosque:L.layerGroup().addTo(map),food:L.layerGroup().addTo(map),place:L.layerGroup().addTo(map)};let places=[],userLat=null,userLng=null,userAccuracy=null,userMarker=null,userCircle=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const nav=p=>`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(p.lat+","+p.lng)}&travelmode=driving`;
function tags(p){let a=[];if(p.verification==="verified_source")a.push("✓ Source found");else if(p.verification==="business_current")a.push("✓ Current listing");else a.push("⚠ Unverified");if(p.type==="mosque"){if(p.sect)a.push("🕌 "+p.sect);if(p.toilet)a.push("🚻 Toilet");if(p.wudu)a.push("💧 Wudu");if(p.wheelchair)a.push("♿ Wheelchair");if(p.women)a.push("👩 Women");if(p.friday)a.push("🕌 Friday")}if(p.type==="food"){if(p.halal)a.push("☪ Halal");if(p.porkFree)a.push("🚫 Pork-free");if(p.vegetarian)a.push("🥗 Vegetarian");if(p.cheap)a.push("💰 Cheap");if(p.atmosphere)a.push("🙂 Nice atmosphere");if(p.delicious)a.push("⭐ Very delicious")}if(p.type==="place"){if(p.entertainment)a.push("🎡 "+p.entertainment);if(p.nature)a.push("🌿 "+p.nature);if(p.religion)a.push("🕊 "+p.religion);if(p.historical)a.push("🏛 Historical");if(p.interesting)a.push("💡 Interesting")}return a.map(x=>`<span>${esc(x)}</span>`).join("")}
function distanceKm(p){if(userLat===null)return null;const R=6371,dLat=(p.lat-userLat)*Math.PI/180,dLon=(p.lng-userLng)*Math.PI/180,a=Math.sin(dLat/2)**2+Math.cos(userLat*Math.PI/180)*Math.cos(p.lat*Math.PI/180)*Math.sin(dLon/2)**2;return R*2*Math.atan2(Math.sqrt(a),Math.sqrt(1-a))}
function popup(p){let d=distanceKm(p);return `<div class="popup"><h3>${esc(p.name)}</h3><div class="badges">${tags(p)}</div>${d!==null?`<p>📏 <b>${d<10?d.toFixed(1):Math.round(d)} km</b> from you</p>`:""}${p.hours?`<p><b>Hours:</b> ${esc(p.hours)}</p>`:""}${p.address?`<p>📍 ${esc(p.address)}</p>`:""}${p.phone?`<p>☎ ${esc(p.phone)}</p>`:""}${p.website?`<p>🌐 <a href="${esc(p.website)}" target="_blank" rel="noopener">Website</a></p>`:""}<p>${esc(p.notes||"")}</p><a class="nav" href="${nav(p)}" target="_blank" rel="noopener">🧭 Navigate with Google Maps</a><p class="small">Source: ${esc(p.source||"")}</p></div>`}
function filterValues(type){const box=document.getElementById(type+"Filters");return box?[...box.querySelectorAll("[data-filter]:checked")].map(x=>x.dataset.filter):[]}
function match(p){const f=filterValues(p.type);if(!f.length)return true;if(p.type==="mosque"||p.type==="food")return f.every(x=>p[x]===true);return f.every(x=>x==="historical"?p.historical===true:x==="interesting"?p.interesting===true:!!p[x])}
function activeDistance(){return document.querySelector('input[name="distance"]:checked')?.value||"all"}
function inDistance(p){if(activeDistance()==="all"||userLat===null)return true;return distanceKm(p)<=Number(activeDistance())}
function makeMarker(p){let ic=p.type==="mosque"?"🕌":p.type==="food"?"🍴":"⭐",near=userLat!==null&&distanceKm(p)<=50;let c="emoji-marker"+(near?" nearby-blink":"");return L.marker([p.lat,p.lng],{title:p.name,icon:L.divIcon({className:c,html:`<div class="marker-icon">${ic}</div>`,iconSize:[115,115],iconAnchor:[57,105],popupAnchor:[0,-100]})}).bindPopup(popup(p))}
function render(){Object.values(groups).forEach(g=>g.clearLayers());for(const p of places){const layer=document.querySelector(`[data-layer="${p.type}"]`);if(!layer||!layer.checked||!match(p)||!inDistance(p))continue;makeMarker(p).addTo(groups[p.type])}}
function visibility(){for(const t of ["mosque","food","place"]){const layer=document.querySelector(`[data-layer="${t}"]`),box=document.getElementById(t+"Filters");if(box)box.style.display=layer&&layer.checked?"block":"none"}render()}
for(const x of document.querySelectorAll("[data-layer]"))x.addEventListener("change",visibility);for(const x of document.querySelectorAll("[data-filter]"))x.addEventListener("change",render);for(const x of document.querySelectorAll('input[name="distance"]'))x.addEventListener("change",render);
document.getElementById("locateBtn").addEventListener("click",()=>{const s=document.getElementById("locationStatus");if(!navigator.geolocation){s.textContent="GPS is not available in this browser.";return}s.textContent="Requesting your location…";navigator.geolocation.getCurrentPosition(pos=>{userLat=pos.coords.latitude;userLng=pos.coords.longitude;userAccuracy=pos.coords.accuracy;const ll=[userLat,userLng];if(userMarker)map.removeLayer(userMarker);if(userCircle)map.removeLayer(userCircle);userMarker=L.marker(ll,{icon:L.divIcon({className:"emoji-marker",html:'<div class="marker-icon">📍</div>',iconSize:[115,115],iconAnchor:[57,105]})}).addTo(map).bindPopup("📍 You are here").openPopup();userCircle=L.circle(ll,{radius:userAccuracy||30,weight:1}).addTo(map);map.setView(ll,14);s.textContent=`📍 Location found. Nearby places within 50 km are blinking. Accuracy about ${Math.round(userAccuracy)} m.`;render()},()=>s.textContent="Location unavailable. Allow GPS access and try again.",{enableHighAccuracy:true,timeout:15000,maximumAge:30000})});
fetch("data/places.json").then(r=>r.json()).then(d=>{places=d;visibility()}).catch(()=>document.getElementById("locationStatus").textContent="Could not load data/places.json.");
